rootProject.name = "coordinatekit-foundation"

include "aggregate-jacoco-gradle"
include "aggregate-javadoc-gradle"
include "changelog-gradle"
include "cli-brand"
include "concordance"
include "concordance-errorprone"
include "concordance-gradle"
include "conventions"
include "third-party-licenses-gradle"
